/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  AdminPolls: () => import('#controllers/admin_polls_controller'),
  Home: () => import('#controllers/home_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  Polls: () => import('#controllers/polls_controller'),
  Session: () => import('#controllers/session_controller'),
}
